import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { formatRecentlyOpened, LibraryView } from "./LibraryView.js";
import type { LibraryBook } from "./library-client.js";
const base = { sourceSha256: "a".repeat(64), sourceSize: 1024, contentKind: "chinese", coverAssetId: null, annotationStatus: "not-applicable", note: "保留数据", addedAt: "2026-08-01T00:00:00Z", updatedAt: "2026-08-02T00:00:00Z" } as const;
const old: LibraryBook = { ...base, id: "01234567-89ab-4cde-8fab-0123456789ab", sourceFileName: "旧书.epub", title: "旧书", authors: ["甲"], collectionStatus: "completed", readingProgress: null };
const recent: LibraryBook = { ...base, id: "11234567-89ab-4cde-8fab-0123456789ab", sourceFileName: "新书.epub", title: "新书", authors: ["乙"], collectionStatus: "reading", readingProgress: { progress: .43, chapterLabel: "第三章", updatedAt: "2026-08-06T00:00:00Z" } };
const renderView = (overrides = {}) => render(<LibraryView books={[old, recent]} selectedBookId={recent.id} onSelect={() => {}} onImport={() => {}} onRead={() => {}} onUpdate={async () => {}} {...overrides} />);
afterEach(cleanup);
describe("LibraryView", () => {
  it("sorts opened books first and exposes sortable four-column headers", async () => { const user = userEvent.setup(); renderView(); const list = screen.getByLabelText("书籍列表"); expect(within(list).getAllByText(/新书|旧书/)[0]).toHaveTextContent("新书"); for (const name of ["书名", "作者", "状态", /最近打开/]) expect(within(list).getByRole("button", { name })).toBeInTheDocument(); await user.click(within(list).getByRole("button", { name: "状态" })); expect(within(list).getAllByRole("button").some((button) => button.textContent?.includes("新书乙在看"))).toBe(true); });
  it("activates a focused filter and supports arrows as well as WASD", async () => { const user = userEvent.setup(); const onSelect = vi.fn(); renderView({ onSelect }); await waitFor(() => expect(within(screen.getByLabelText("书籍列表")).getByRole("button", { name: /新书/ })).toHaveFocus()); await user.keyboard("a"); expect(within(screen.getByLabelText("藏书状态")).getByRole("button", { name: "全部2" })).toHaveFocus(); await user.keyboard("{ArrowDown}"); expect(within(screen.getByLabelText("藏书状态")).getByRole("button", { name: "想看0" })).toHaveAttribute("aria-pressed", "true"); });
  it("compacts details and keeps all five operations", () => { renderView(); const detail = screen.getByLabelText("书籍详情"); expect(detail).toHaveTextContent("纯中文 · 无需程序注音 · 1.0 KB"); expect(detail).toHaveTextContent("43% · 第三章"); expect(screen.queryByRole("textbox", { name: "备注" })).not.toBeInTheDocument(); for (const name of ["继续阅读", "从头阅读", "重新导入", "删除当前书籍"]) expect(within(detail).getByRole("button", { name })).toBeInTheDocument(); expect(within(detail).getByRole("link", { name: "导出 EPUB" })).toHaveAttribute("download", "新书.epub"); });
  it("updates status and invokes maintenance actions", async () => { const user = userEvent.setup(); const onUpdate = vi.fn(async () => {}); const onReimport = vi.fn(); const onDelete = vi.fn(); renderView({ onUpdate, onReimport, onDelete }); await user.click(screen.getByRole("button", { name: "看过" })); expect(onUpdate).toHaveBeenCalledWith(recent.id, { collectionStatus: "completed" }); await user.click(screen.getByRole("button", { name: "重新导入" })); await user.click(screen.getByRole("button", { name: "删除当前书籍" })); expect(onReimport).toHaveBeenCalledWith(recent.id); expect(onDelete).toHaveBeenCalledWith(recent.id); });
  it("formats recent reading time without using library updatedAt", () => { expect(formatRecentlyOpened(old, new Date("2026-08-06T12:00:00Z"))).toBe("未打开"); expect(formatRecentlyOpened(recent, new Date("2026-08-06T12:00:00Z"))).toBe("今天"); });
});
