import { useCallback, useEffect, useRef, useState, type ChangeEvent } from "react";
import { cloneReaderSettings, parseReaderAppearance, type ReaderAppearance, type ReaderSettings, type ThemeMode } from "./reader-settings.js";
import { useSpatialNavigation } from "./spatial-navigation.js";
import { BUILTIN_THEME_IDS, parseThemeDefinition, type ThemeDefinition } from "./themes.js";
import type { AvailableTheme } from "./theme-client.js";

interface SettingsPanelProps {
  settings: ReaderSettings; themes: AvailableTheme[]; scope?: "library" | "reader"; embedded?: boolean;
  onPreview(settings: ReaderSettings): void; onSave(settings: ReaderSettings): Promise<void>;
  onImport(theme: ThemeDefinition): Promise<AvailableTheme>; onThemesChange(themes: AvailableTheme[]): void; onClose?(): void;
}
type NumberKey = keyof ReaderAppearance["typography"];
const NUMBER_FIELDS: Array<{ key: NumberKey; label: string; min: number; max: number; step: number; suffix: string }> = [
  { key: "fontSize", label: "字号", min: 14, max: 30, step: 1, suffix: "px" }, { key: "rubyScale", label: "注音字号", min: 0.45, max: 0.8, step: 0.05, suffix: "倍" },
  { key: "lineHeight", label: "段内间距", min: 1.4, max: 2.2, step: 0.05, suffix: "倍" }, { key: "paragraphSpacing", label: "段落间距", min: 0, max: 2, step: 0.1, suffix: "em" },
  { key: "columnWidth", label: "栏宽", min: 520, max: 1200, step: 10, suffix: "px" }, { key: "japaneseOpacity", label: "日文透明度", min: 0.2, max: 1, step: 0.05, suffix: "" },
];
function typographyInputs(appearance: ReaderAppearance): Record<NumberKey, string> { return Object.fromEntries(NUMBER_FIELDS.map(({ key }) => [key, String(appearance.typography[key])])) as Record<NumberKey, string>; }

export function SettingsPanel({ settings, themes, scope = "reader", embedded = false, onPreview, onSave, onImport, onThemesChange, onClose }: SettingsPanelProps) {
  const rootRef = useRef<HTMLDivElement>(null); const fileRef = useRef<HTMLInputElement>(null); const persistedRef = useRef(cloneReaderSettings(settings)); const draftRef = useRef(cloneReaderSettings(settings)); const timerRef = useRef<number | undefined>(undefined);
  const [draft, setDraft] = useState(() => cloneReaderSettings(settings)); const [numbers, setNumbers] = useState(() => typographyInputs(settings.appearance)); const [editing, setEditing] = useState(false); const [replaceTheme, setReplaceTheme] = useState<ThemeDefinition>(); const [localError, setLocalError] = useState<string>();
  useEffect(() => { draftRef.current = cloneReaderSettings(settings); setDraft(cloneReaderSettings(settings)); setNumbers(typographyInputs(settings.appearance)); }, [settings]);
  const persist = useCallback(async (next = draftRef.current) => { if (timerRef.current) clearTimeout(timerRef.current); try { await onSave(next); persistedRef.current = cloneReaderSettings(next); } catch { const rollback = cloneReaderSettings(persistedRef.current); draftRef.current = rollback; setDraft(rollback); setNumbers(typographyInputs(rollback.appearance)); onPreview(rollback); } }, [onPreview, onSave]);
  const updateSettings = useCallback((next: ReaderSettings, immediate = false) => { draftRef.current = next; setDraft(next); setNumbers(typographyInputs(next.appearance)); onPreview(next); if (timerRef.current) clearTimeout(timerRef.current); if (immediate) void persist(next); else timerRef.current = window.setTimeout(() => void persist(next), 300); }, [onPreview, persist]);
  const updateAppearance = (appearance: ReaderAppearance, immediate = false): void => updateSettings({ ...draftRef.current, appearance }, immediate);
  useSpatialNavigation({ rootRef, enabled: !embedded, editing, keys: "both", onActivate: (element) => { if (!element.classList.contains("appearance-number-entry")) return false; setEditing(true); requestAnimationFrame(() => { const input = element.querySelector("input"); input?.focus(); input?.select(); }); return true; } });
  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);
  const close = async (): Promise<void> => { await persist(); onClose?.(); };
  useEffect(() => { if (embedded) return; const listener = (event: KeyboardEvent) => { if (event.key === "Escape" && !editing && !replaceTheme) { event.preventDefault(); void close(); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); });
  const updateNumber = (key: NumberKey, raw: string, sync = false): void => { if (!sync) setNumbers((current) => ({ ...current, [key]: raw })); const appearance = parseReaderAppearance({ ...draftRef.current.appearance, typography: { ...draftRef.current.appearance.typography, [key]: Number(raw) } }); if (appearance && raw.trim()) updateAppearance(appearance); };
  const selectTheme = (id: string, variant: "light" | "dark"): void => updateAppearance({ ...draft.appearance, theme: { ...draft.appearance.theme, [variant === "light" ? "lightThemeId" : "darkThemeId"]: id } }, true);
  const importTheme = async (theme: ThemeDefinition): Promise<void> => { try { setLocalError(undefined); const imported = await onImport(theme); onThemesChange([...themes.filter((item) => item.theme.id !== theme.id), imported]); selectTheme(theme.id, theme.variant); } catch (error) { setLocalError((error as Error).message); } };
  const onFile = async (event: ChangeEvent<HTMLInputElement>): Promise<void> => { const file = event.currentTarget.files?.[0]; event.currentTarget.value = ""; if (!file) return; try { if (file.size > 64 * 1024) throw new Error("主题文件不能超过 64 KB。"); const theme = parseThemeDefinition(JSON.parse(await file.text())); if (!theme) throw new Error("主题 JSON 不符合 Airnobe 主题格式。"); if (BUILTIN_THEME_IDS.has(theme.id)) throw new Error("不能覆盖内置主题。"); if (themes.some((item) => item.theme.id === theme.id && !item.builtin)) setReplaceTheme(theme); else await importTheme(theme); } catch (error) { setLocalError((error as Error).message); } };
  const content = <div className={`settings-panel${embedded ? " settings-panel--embedded" : ""}`} ref={rootRef} role={embedded ? undefined : "dialog"} aria-modal={embedded ? undefined : true} aria-label={embedded ? undefined : scope === "library" ? "书库设置" : "阅读设置"}>
    {!embedded && <header><h2>{scope === "library" ? "书库设置" : "阅读设置"}</h2><button type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row="0" onClick={() => void close()} aria-label="关闭设置">×</button></header>}
    <section><h3>主题</h3><div className="settings-choice-row"><span>模式</span>{([ ["day", "日间"], ["night", "夜间"], ["system", "跟随系统"] ] as const).map(([mode, label]) => <button key={mode} type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row="1" aria-pressed={draft.appearance.theme.mode === mode} onClick={() => updateAppearance({ ...draft.appearance, theme: { ...draft.appearance.theme, mode: mode as ThemeMode } }, true)}>{label}</button>)}</div>
      {([ ["light", "日间主题"], ["dark", "夜间主题"] ] as const).map(([variant, label], group) => <div key={variant}><h4>{label}</h4><div className="theme-options">{themes.filter((item) => item.theme.variant === variant).map((item, index) => <button key={item.theme.id} type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row={String(2 + group * 10 + index)} aria-pressed={draft.appearance.theme[variant === "light" ? "lightThemeId" : "darkThemeId"] === item.theme.id} onClick={() => selectTheme(item.theme.id, variant)}><i style={{ background: item.theme.colors.background }} /><i style={{ background: item.theme.colors.accent }} /><span>{item.theme.name}</span></button>)}</div></div>)}
      <input ref={fileRef} className="file-input" type="file" accept="application/json,.json" onChange={(event) => void onFile(event)} /><button type="button" className="secondary-action settings-import" data-spatial-item data-spatial-zone="settings" data-spatial-row="22" onClick={() => fileRef.current?.click()}>导入主题 JSON</button></section>
    {scope === "reader" && <><section><h3>排版与样式</h3>{NUMBER_FIELDS.map((field, index) => <label className="appearance-number" key={field.key}><span>{field.label}</span><input className="appearance-slider" aria-label={`${field.label}滑块`} type="range" min={field.min} max={field.max} step={field.step} value={draft.appearance.typography[field.key]} onChange={(event) => updateNumber(field.key, event.target.value, true)} /><span className="appearance-number-entry" tabIndex={0} data-spatial-item data-spatial-zone="settings" data-spatial-row={String(30 + index)}><input aria-label={field.label} type="number" min={field.min} max={field.max} step={field.step} value={numbers[field.key]} onFocus={() => setEditing(true)} onBlur={() => { setEditing(false); setNumbers(typographyInputs(draftRef.current.appearance)); }} onChange={(event) => updateNumber(field.key, event.target.value)} />{field.suffix}</span></label>)}
      <div className="settings-choice-row"><span>字重</span>{([400, 600] as const).map((weight) => <button key={weight} type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row="36" aria-pressed={draft.appearance.typography.fontWeight === weight} onClick={() => updateAppearance({ ...draft.appearance, typography: { ...draft.appearance.typography, fontWeight: weight } })}>{weight === 400 ? "正常 400" : "半粗 600"}</button>)}</div>
      {([ ["showJapanese", "显示日文"], ["showAssistedRuby", "显示振假名"], ["showKatakanaRomaji", "显示片假名罗马音"], ["showJapaneseRule", "显示日文引用线"], ["showProgressBars", "显示阅读进度条"] ] as const).map(([key, label], index) => <button className="settings-toggle" key={key} type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row={String(37 + index)} aria-pressed={draft.appearance.display[key]} onClick={() => updateAppearance({ ...draft.appearance, display: { ...draft.appearance.display, [key]: !draft.appearance.display[key] } }, true)}><span>{label}</span><b>{draft.appearance.display[key] ? "开" : "关"}</b></button>)}
      <button className="settings-toggle" type="button" data-spatial-item data-spatial-zone="settings" data-spatial-row="42" aria-pressed={draft.pageTransitions} onClick={() => updateSettings({ ...draftRef.current, pageTransitions: !draftRef.current.pageTransitions }, true)}><span>翻页淡入淡出</span><b>{draft.pageTransitions ? "开" : "关"}</b></button></section></>}
    {localError && <p className="settings-error" role="alert">{localError}</p>}{replaceTheme && <div className="settings-confirm"><p>替换同名自定义主题“{replaceTheme.name}”？</p><button type="button" onClick={() => { const theme = replaceTheme; setReplaceTheme(undefined); void importTheme(theme); }}>替换</button><button type="button" onClick={() => setReplaceTheme(undefined)}>取消</button></div>}
  </div>;
  return embedded ? content : <div className="settings-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) void close(); }}>{content}</div>;
}
