import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { SettingsPanel } from "./SettingsPanel.js";
import { DEFAULT_READER_SETTINGS } from "./reader-settings.js";
import { builtinThemeOptions } from "./theme-client.js";
afterEach(cleanup);
const props = { settings: DEFAULT_READER_SETTINGS, themes: builtinThemeOptions(), onSave: async () => {}, onImport: async () => { throw new Error("unused"); }, onThemesChange: () => {}, onClose: () => {} };
describe("SettingsPanel", () => {
  it("previews reader typography and global display state", () => { const preview = vi.fn(); render(<SettingsPanel {...props} scope="reader" onPreview={preview} />); fireEvent.change(screen.getByLabelText("字号滑块"), { target: { value: "23" } }); expect(preview).toHaveBeenLastCalledWith(expect.objectContaining({ appearance: expect.objectContaining({ typography: expect.objectContaining({ fontSize: 23 }) }) })); fireEvent.click(screen.getByRole("button", { name: "显示日文关" })); expect(preview).toHaveBeenLastCalledWith(expect.objectContaining({ appearance: expect.objectContaining({ display: expect.objectContaining({ showJapanese: true }) }) })); expect(screen.getByLabelText("注音字号")).toHaveAttribute("min", "0.45"); });
  it("shows only themes for the effective light or dark mode", () => { render(<SettingsPanel {...props} scope="library" onPreview={() => {}} />); expect(screen.getByRole("button", { name: "系统" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "暖纸" })).not.toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "浅色" })); expect(screen.getByRole("button", { name: "暖纸" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Airnobe Night" })).not.toBeInTheDocument(); expect(screen.queryByLabelText("字号")).not.toBeInTheDocument(); });
  it("supports bold weight and limits navigation steps to ten", () => { const preview = vi.fn(); render(<SettingsPanel {...props} scope="reader" onPreview={preview} />); fireEvent.click(screen.getByRole("button", { name: "粗体" })); expect(preview).toHaveBeenLastCalledWith(expect.objectContaining({ appearance: expect.objectContaining({ typography: expect.objectContaining({ fontWeight: 800 }) }) })); expect(screen.getByRole("spinbutton", { name: "回退/快进段数" })).toHaveAttribute("max", "10"); fireEvent.change(screen.getByLabelText("回退/快进段数滑块"), { target: { value: "7" } }); expect(preview).toHaveBeenLastCalledWith(expect.objectContaining({ navigation: { textSteps: 7 } })); });
});
